### ISSUE TITLE
Kernel Panic

### ISSUE THREAD

**Issue by 1kevin335200** [Piker-Alpha/AppleIntelInfo#10]
os x 10.11.6
Thinkpad x240
CPU:core i5 4200u
Compiled the kext and use kext utility to inject it,after reboot it gets kernel panic.
delete /system/extensions/appleintelinfo.kext and start with no caches and kexts doesn't help.
![img_20160820_191103](https://cloud.githubusercontent.com/assets/15524267/17830846/65396eac-670b-11e6-806d-ba52cac287ae.jpg)

**Comment by 1kevin335200** [comment]
i had already delete /system/library/caches,but i can still not run in single user mode.
Maybe something wrong with nvram.

**Comment by Piker-Alpha** [comment]
The kext must be loaded dynamically and not be part of the prelinkedkernel cache i.e. do not copy it to /Library/Extensions/ or /System/Library/Extensions/ and also do not inject it from the boot loader at boot time.
