### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by philippetev** [Piker-Alpha/AppleIntelInfo#16]
It seems there is something wrong with the latest code. This is what I get when trying to load the kext in 10.11.6:

**philip@ProBook-4340s:$ sudo kextload /Users/philip/Desktop/AppleIntelInfo.kext/
/Users/philip/Desktop/AppleIntelInfo.kext failed to load - (libkern/kext) dependency resolution failure; check the system/kernel logs for errors or try kextutil(8).
philip@ProBook-4340s:$ sudo kextutil /Users/philip/Desktop/AppleIntelInfo.kext/
/Users/philip/Desktop/AppleIntelInfo.kext - no compatible dependency found for com.apple.kpi.mach.
/Users/philip/Desktop/AppleIntelInfo.kext - no compatible dependency found for com.apple.kpi.iokit.
/Users/philip/Desktop/AppleIntelInfo.kext - no compatible dependency found for com.apple.kpi.libkern.
/Users/philip/Desktop/AppleIntelInfo.kext - no compatible dependency found for com.apple.kpi.bsd.
/Users/philip/Desktop/AppleIntelInfo.kext - no compatible dependency found for com.apple.kpi.mach.
/Users/philip/Desktop/AppleIntelInfo.kext - no compatible dependency found for com.apple.kpi.iokit.
/Users/philip/Desktop/AppleIntelInfo.kext - no compatible dependency found for com.apple.kpi.libkern.
/Users/philip/Desktop/AppleIntelInfo.kext - no compatible dependency found for com.apple.kpi.bsd.
/Users/philip/Desktop/AppleIntelInfo.kext - no compatible dependency found for com.apple.kpi.mach.
/Users/philip/Desktop/AppleIntelInfo.kext - no compatible dependency found for com.apple.kpi.iokit.
/Users/philip/Desktop/AppleIntelInfo.kext - no compatible dependency found for com.apple.kpi.libkern.
/Users/philip/Desktop/AppleIntelInfo.kext - no compatible dependency found for com.apple.kpi.bsd.
Diagnostics for /Users/philip/Desktop/AppleIntelInfo.kext:
Dependency Resolution Failures:
    Only incompatible kexts found for these libraries:
        com.apple.kpi.mach
        com.apple.kpi.iokit
        com.apple.kpi.libkern
        com.apple.kpi.bsd
Code Signing Failure: not code signed
philip@ProBook-4340s:~$**

There is no such problem with the old version 2.2.

Edit: Are you sure there is no typo in **AppleIntelInfo.kext/Contents/info.plist**? All dependencies are set to 16.5, but in macOS 10.11.6 all those personalities are in version 15.6.

**Comment by philippetev** [comment]
Are you sure there is no typo here:

**<dict>
		<key>com.apple.kpi.bsd</key>
		<string>16.5</string>
		<key>com.apple.kpi.iokit</key>
		<string>16.5</string>
		<key>com.apple.kpi.libkern</key>
		<string>16.5</string>
		<key>com.apple.kpi.mach</key>
		<string>16.5</string>
		<key>com.apple.kpi.unsupported</key>
		<string>10.5</string>
</dict>**

16.5? All those kexts on my install are version 15.6.

**Comment by MacNB** [comment]
Ditto same problem.
I changed the Info.plist dependencies from 16.5 to 15.6 and it loads but reboots my laptop (i5-2410M CPU). previous version (v2.2) worked fine on the same laptop.

**Comment by Piker-Alpha** [comment]
Thanks. Changes undone with latest commits.
