### ISSUE TITLE
v2.5 (currently latest) KP on Core m5 (Skylake), with macOS Sierra 10.12.5 (16F43c).

### ISSUE THREAD

**Issue by PMheart** [Piker-Alpha/AppleIntelInfo#18]
Hi. Pike.
First of all kudos for this amazing repository!
It's a pity that I always encounter a KP with the currently latest version 2.5, seems to be the problem of reading MSRs, well, I dunno details to be honest.
Anything else I need to post here?
And any kinds of help will be appreciated, thanks!

PMheart

**Comment by Piker-Alpha** [comment]
Take a look at this code snippet:
```
#define REPORT_MSRS				1
#define REPORT_RAPL_MSRS		1
#define REPORT_HWP				1
#define REPORT_HDC				1

#define REPORT_IGPU_P_STATES	1
#define REPORT_C_STATES			1
#define REPORT_IPG_STYLE		1
#define REPORT_INTEL_REGS		0
```
This lets you disable certain code sections. Please change all but REPORT_MSRS to 0 and compile/reboot. KP solved? Then re-enable them one after the other. KP still not solved, too bad, but at least now we have limited the scope of the problem. Making it easier to fix.

**Comment by PMheart** [comment]
Great, I may test and report it in a couple of days.

Thanks Pike!

**Comment by Piker-Alpha** [comment]
Any news?

**Comment by PMheart** [comment]
Hi Pike! Sorry I was so busy that I’d almost forgotten this issue. But anyway seemingly the latest version of AppleIntelInfo works fine here, thanks anyway!
