### ISSUE TITLE
Accidentally installed AppleIntelInfo.kext via kext installer

### ISSUE THREAD

**Issue by KalWardin** [Piker-Alpha/AppleIntelInfo#20]
Hey Pike,

while following a guide on enabling native PM, which read 'install' the kext, I rendered my machine unbootable (kernel panic). Having done some digging, I was able to remove the kext using a bootable UniBeast stick and boot into Sierra again. However, a window saying the kext has been installed improperly has kept popping up ever since, although the latter's been seemingly removed from the system along with its cache. Additionally, my audio is now greyed out. May I ask what the solution may be? 

Many thanks in advance,
Kal

**Comment by Piker-Alpha** [comment]
Hi,

Sorry for being late. Still on holidays. Anyway. Do you know where the kext have been installed? Is that:
/Library/Extensions or /System/Library/Extensions?

When you know where the kext is installed, then you should boot from another volume (think recoveryOS) and remove the kext with sudo rm [path]/AppleIntelInfo.kext

**Note**: you should never install this kext in either directory, but load it when you need it!

**Comment by KalWardin** [comment]
Hey,

You’re all right :) I’ve already deleted the kext using the following command sequence: 

diskutil mount /dev/DiskNumber
cd /Volumes/VolumeName

cd /System/Library/Extensions

rm -rf /System/Library/Extensions/RealtekRTL81xx.kext

rm -rf /System/Library/Caches/*

However, I suspect the system’s not fully operational with respect to CPU PM. May you please assist me with that? The folks on tonymac aren’t exactly co-operative :)

Yours sincerely,
Alex

**Comment by Piker-Alpha** [comment]
Hi Alex,

Sorry, but that is off-topic. I'm also too busy keeping up with everything already. No time.

**Comment by KalWardin** [comment]
No problemo! Thank you, anyway. 

Regards,
Alex
