### ISSUE TITLE
States shown, but are never reached

### ISSUE THREAD

**Issue by Simanias** [Piker-Alpha/AppleIntelInfo#6]
Pike,
I was under the impression that the states which are shown in the console are actually reached, but I was testing the old AppleIntelCPUPowerManagmentInfo.kext and it only showed three states:

20/01/15 20:38:26,000 kernel[0]: AICPUPMI: CPU P-States [ 8 35 39 ]

When I load the AppleIntelInfo.kext it shows:

20/01/15 20:35:13,000 kernel[0]: AICPUPMI: CPU P-States [ (8) 11 12 13 14 15 16 17 18 19 20 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 ] iGPU P-States [ (25) ]

However if I look more closely in the console only the states 8, 35, 39 have (x) marks, so the others are never actually running.
Any thoughts?
Simania

**Comment by Piker-Alpha** [comment]
Sorry for the ultra late reply, but this is correct. It all depends on the settings in the Info.plist. You are using the default settings, with logIPGStyle (Intel Power Gadget Style) being set to YES (1) but the old kext did not support this and thus won't show all states, like the Intel Power Gadget does!
