### ISSUE TITLE
Kernel Panic

### ISSUE THREAD

**Issue by bolemo** [Piker-Alpha/AppleIntelInfo#8]
Mac OS X 10.10.5
Hackintosh Asus X99 Deluxe w/ intel i7 4820K Haswell-E
Chimera
XCode 6.4
Compiled for 10.10 environment and target, and tried also 10.8 as said in this tutorial : http://www.insanelymac.com/forum/topic/304369-how-to-check-your-states-%E2%80%93-using-aicpminfo-msrdumper-or-appleintelinfo/

Problem is: instant kernel panic when kext is enabled.

**Comment by flow555** [comment]
Same problem on a similar system
- Asus X99-A USB 3.1
- i7 5820k (should be the same as bolemo -> typo!)
- Clover
- OS X 10.11.2
- Xcode 7.2

Compiled with no change

Since I don't know details I just testet different settings to reproduce the kernel panic.
__The crucial setting is the logMSRs value. With this at no/false everything works just fine.__
Maybe this is in relation with the MSR register restriction, I read on http://clover-wiki.zetam.org/Configuration/KernelAndKextPatches#kernelandkextpatches_asusaicpupm


Here is my AppleIntelInfo.dat
```
AppleIntelInfo.kext v1.2 Copyright © 2012-2015 Pike R. Alpha. All rights reserved

Settings:
------------------------------------
logMSRs............................: 0
logIGPU............................: 0
logIntelRegs.......................: 1
logCStates.........................: 1
logIPGStyle........................: 1
InitialTSC.........................: 0x50a2efb6d47
MWAIT C-States.....................: 8480
PCH device.................: 0x8D478086

CPU Ratio Info:
------------------------------------
CPU Low Frequency Mode.............: 1200 MHz
CPU Maximum non-Turbo Frequency....: 3300 MHz
CPU Maximum Turbo Frequency........: 3600 MHz
CPU P-States [ 23 (33) ]
CPU C6-Cores [ 1 2 4 6 8 10 ]
CPU P-States [ (12) 23 24 33 ]
CPU P-States [ (12) 23 24 28 33 ]
CPU P-States [ (12) 19 23 24 28 33 ]
CPU C6-Cores [ 1 2 3 4 6 8 10 ]
CPU P-States [ (12) 19 23 24 25 28 33 ]
CPU C6-Cores [ 1 2 3 4 5 6 8 10 ]
CPU C6-Cores [ 0 1 2 3 4 5 6 8 10 11 ]
CPU P-States [ (12) 19 23 24 25 28 30 33 ]
CPU C6-Cores [ 0 1 2 3 4 5 6 8 9 10 11 ]
CPU P-States [ 12 19 23 24 25 28 29 30 (33) ]
CPU P-States [ 12 19 23 24 25 28 29 30 33 (34) ]
CPU P-States [ (12) 19 23 24 25 28 29 30 31 33 34 ]
CPU C6-Cores [ 0 1 2 3 4 5 6 7 8 9 10 11 ]
CPU P-States [ 12 19 23 24 25 28 29 30 31 32 (33) 34 ]
[...]
CPU P-States [ (12) 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 36 ]
```

**Comment by abelletti** [comment]
Just a quick "me too":

ASRock X99 Extreme4
i7-5820k
Clover 3333
OSX 10.11.3
XCode 7.2

Thanks flow555 for finding the workaround (turning off logMSRs) which worked for me as well.

AppleIntelInfo.kext v1.2 Copyright © 2012-2015 Pike R. Alpha. All rights reserved

Settings:
------------------------------------
logMSRs............................: 0
logIGPU............................: 0
logIntelRegs.......................: 1
logCStates.........................: 1
logIPGStyle........................: 1
InitialTSC.........................: 0x27482c05c7d3a
MWAIT C-States.....................: 8480

CPU Ratio Info:
------------------------------------
CPU Low Frequency Mode.............: 1200 MHz
CPU Maximum non-Turbo Frequency....: 3300 MHz
CPU Maximum Turbo Frequency........: 3600 MHz
CPU P-States [ (12) 24 33 ]
CPU C6-Cores [ 1 2 4 7 8 10 11 ]
CPU P-States [ (12) 13 24 33 ]
CPU C6-Cores [ 1 2 3 4 5 7 8 9 10 11 ]
CPU P-States [ (12) 13 23 24 33 ]
CPU C6-Cores [ 1 2 3 4 5 6 7 8 9 10 11 ]
CPU P-States [ (12) 13 23 24 25 33 ]
CPU P-States [ 12 13 23 24 25 27 (33) ]
CPU P-States [ (12) 13 22 23 24 25 27 33 ]
CPU P-States [ (12) 13 15 22 23 24 25 27 33 ]
CPU C6-Cores [ 0 1 2 3 4 5 6 7 8 9 10 11 ]
CPU P-States [ (12) 13 15 21 22 23 24 25 27 33 ]
CPU P-States [ (12) 13 15 20 21 22 23 24 25 27 33 ]
CPU P-States [ (12) 13 15 16 20 21 22 23 24 25 27 33 ]
CPU P-States [ (12) 13 15 16 20 21 22 23 24 25 27 28 33 ]
CPU P-States [ (12) 13 15 16 19 20 21 22 23 24 25 27 28 33 ]

**Comment by Piker-Alpha** [comment]
Oh great. I was unaware of any issues until I made a couple of small changes. Sorry folks.

Let see. Reading reserved or unsupported MSR's will usually end in a KP so what is the last line you see in /tmp/AppleIntelInfo.dat when it crashes?

What you can do is to comment out the C7 MSR's and see if that is causing the KP. If not, then please comment out the rest (one by one) and let me know what we need to fix. 

Thanks!

**Comment by flow555** [comment]
Hi Piker-Apha,

there is no file generated in the first place. I also changed the .dat path to another in case OS X somehow delete the file in the /tmp directory. There is definitely no file generated.

Sorry, but I have not enough free time/know-how to read through your code. If you write exactly which lines you mean, I maybe can try it on Sunday.

**Comment by Piker-Alpha** [comment]
Let's start with a link to the file: https://github.com/Piker-Alpha/AppleIntelInfo/blob/master/AppleIntelInfo/AppleIntelInfo.cpp

What you can do is to add a return(); statement on line 105. If that works move in to line 128. If that works move it to line 145. Then line 163 and so on. That will tell you what line(s) are causing the KP.

If you get the KP with the return(); statement on line 128 then there is something wrong with the detection of the IGPU (igpuEnabled should be false).

**Comment by flow555** [comment]
Ok i just tested it. Indeed the KP occurred with "return;" at line 128. My processor doesn't have an internal GPU.

**Comment by Piker-Alpha** [comment]
Ah right. Just what I expected. Question. Did you set 'logIGPU' in AppleIntelInfo.kext/C*/Info.plist to false (before) when that KP occurred? Please try that without any changes to the source code (no additional return statements).

If you get the KP with that setting changed, then change this line: https://github.com/Piker-Alpha/AppleIntelInfo/blob/master/AppleIntelInfo/AppleIntelInfo.h#L40
From 1 to 0 and re-compile it.

Oh and you don't happen to have the kext in /Library/Extensions or /System/Library/Extensions or inject it with Clover?

**Comment by flow555** [comment]
With disabled logIGPU there is still a KP.
With REPORT_IGPU_P_STATES defined as 0 I had to comment out [line 311 in AppleIntelInfo.cpp](https://github.com/Piker-Alpha/AppleIntelInfo/blob/master/AppleIntelInfo/AppleIntelInfo.cpp#311) to compile it.

**Comment by llamafilm** [comment]
Similar problem here.  I run OS 10.10.5 on a Gigabyte GA-X99-Designare with i7-6950x.  When I load the kext, I get an instant reboot.  I tried adding **return;** to line 105 as you suggested above, but still got the reboot.

**Comment by Piker-Alpha** [comment]
@llamafilm,

Thanks. This issue should now been resolved. Please verify/confirm.

**Comment by llamafilm** [comment]
@Piker-Alpha yep, that fixed it.  Interestingly, this tool now shows two P-States for my machine `CPU P-States [ 39 (40) ]`
Before it only showed one.  And MSRDumper.kext still shows only one.  I think SpeedStep is not working for my machine.

I haven't heard of AppleLPC before, but it does not appear in kextstat.  Maybe that's a problem, I'll look into it.

**Comment by Piker-Alpha** [comment]
This is the output that I have got with the i7-6800K: `CPU P-States [ 29 33 34 (35) ]`
Even with a 4GHz OC it won't go over 35. Something is seriously wrong with the firmware or BIOS.

**Comment by llamafilm** [comment]
Maybe this isn't the best place for discussion, but I did get that kext loading by using FakeLPC in Clover. Haven't noticed any difference after that though.

**Comment by flow555** [comment]
Hi,
Downloaded -> Compiled -> Loaded -> everything works fine for me.
Here is my output:
`
AppleIntelInfo.kext v1.5 Copyright © 2012-2016 Pike R. Alpha. All rights reserved

Settings:
------------------------------------
logMSRs............................: 1
logIGPU............................: 0
logCStates.........................: 1
logIPGStyle........................: 1
InitialTSC.........................: 0x118369ec7c70
MWAIT C-States.....................: 8480

Model Specific Registers
-----------------------------------
MSR_CORE_THREAD_COUNT......(0x35)  : 0x6000C
MSR_PLATFORM_INFO..........(0xCE)  : 0x80C3BF3812100
MSR_PMG_CST_CONFIG_CONTROL.(0xE2)  : 0x8400
MSR_PMG_IO_CAPTURE_BASE....(0xE4)  : 0x10414
IA32_MPERF.................(0xE7)  : 0x5A0F1A5023
IA32_APERF.................(0xE8)  : 0x459E678114
MSR_FLEX_RATIO.............(0x194) : 0xE0000
MSR_IA32_PERF_STATUS.......(0x198) : 0x168A00000C00
MSR_IA32_PERF_CONTROL......(0x199) : 0x2400
IA32_CLOCK_MODULATION......(0x19A) : 0x0
IA32_THERM_STATUS..........(0x19C) : 0x88410000
IA32_MISC_ENABLES..........(0x1A0) : 0x850089
MSR_MISC_PWR_MGMT..........(0x1AA) : 0x400001
MSR_TURBO_RATIO_LIMIT......(0x1AD) : 0x2222222222222424
IA32_ENERGY_PERF_BIAS......(0x1B0) : 0x5
MSR_POWER_CTL..............(0x1FC) : 0x2B04005B
MSR_RAPL_POWER_UNIT........(0x606) : 0xA0E03
MSR_PKG_POWER_LIMIT........(0x610) : 0x7FFF80015FFF8
MSR_PKG_ENERGY_STATUS......(0x611) : 0x23971CD
MSR_PKG_POWER_INFO.........(0x614) : 0x1280460
MSR_PP0_POWER_LIMIT........(0x638) : 0x0
MSR_PP0_ENERGY_STATUS......(0x639) : 0x0
MSR_PKGC6_IRTL.............(0x60b) : 0x0
MSR_PKG_C2_RESIDENCY.......(0x60d) : 0x0
MSR_PKG_C6_RESIDENCY.......(0x3f9) : 0x0
IA32_TSC_DEADLINE..........(0x6E0) : 0x11836C0541D7

CPU Ratio Info:
------------------------------------
CPU Low Frequency Mode.............: 1200 MHz
CPU Maximum non-Turbo Frequency....: 3300 MHz
CPU Maximum Turbo Frequency........: 3600 MHz
CPU P-States [ (12) 23 ]
CPU C6-Cores [ 0 2 4 6 8 10 ]
CPU P-States [ 12 19 23 (33) ]
CPU C6-Cores [ 0 2 4 6 8 9 10 ]
CPU P-States [ 12 19 23 25 (33) ]
CPU P-States [ 12 13 19 23 25 (33) ]
CPU P-States [ (12) 13 17 19 23 25 33 ]
CPU P-States [ 12 13 17 19 23 25 30 (33) ]
CPU C6-Cores [ 0 2 3 4 5 6 8 9 10 ]
CPU C6-Cores [ 0 2 3 4 5 6 7 8 9 10 ]
CPU P-States [ (12) 13 17 19 23 25 30 31 33 ]
CPU P-States [ (12) 13 17 19 23 24 25 30 31 33 ]
CPU P-States [ (12) 13 16 17 19 23 24 25 30 31 33 ]
CPU P-States [ (12) 13 16 17 19 23 24 25 26 30 31 33 ]
CPU P-States [ (12) 13 16 17 19 21 23 24 25 26 30 31 33 ]
CPU P-States [ (12) 13 15 16 17 19 21 23 24 25 26 30 31 33 ]
CPU P-States [ (12) 13 15 16 17 18 19 21 23 24 25 26 30 31 33 ]
CPU P-States [ (12) 13 15 16 17 18 19 21 23 24 25 26 27 30 31 33 ]
CPU C6-Cores [ 0 1 2 3 4 5 6 7 8 9 10 ]
CPU P-States [ (12) 13 14 15 16 17 18 19 21 23 24 25 26 27 30 31 33 ]
CPU P-States [ (12) 13 14 15 16 17 18 19 20 21 23 24 25 26 27 30 31 33 ]
CPU P-States [ 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 30 31 (33) ]
CPU C6-Cores [ 0 1 2 3 4 5 6 7 8 9 10 11 ]
CPU P-States [ (12) 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 29 30 31 33 ]
CPU P-States [ (12) 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 33 ]
CPU P-States [ 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 33 (34) ]
CPU P-States [ 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 33 34 (36) ]
CPU P-States [ 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 (33) 34 36 ]
`
